version: '2'

services:
  diagnosis:
    labels:
      category: "web"
      challenge_name: "diagnosis"
      difficulty: "low"
    container_name: kctf-2026-web-diagnosis
    image: kctf-2026/web-diagnosis:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "12082:80"
