version: '3'

services:
  statistics:
    labels:
      category: "web"
      challenge_name: "statistics"
      difficulty: "low"
    container_name: kctf-2026-web-statistics
    image: kctf-2026/web-statistics:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "12084:80"

  statistics-database:
    labels:
      category: "statistics-database"
    container_name: kctf-2026-web-statistics-database
    image: mariadb:10.5.13
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - TZ=Asia/Seoul

    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
